remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: 我的旅遊日記
description: "由布院之旅記錄"

# 側邊欄設定
nav_order: 1
nav:
  - title: Day 1
    url: /day1
  - title: Day 4
    url: /day4
  - title: Day 5
    url: /day5
